name: Alerta DevOps

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificación
        run: |
          curl \
            -H "Title: GitHub Actions - ITLA" \
            -H "Priority: default" \
            -H "Tags: devops, alert, github" \
            -d "Se ha realizado un push en la rama main. Por parte de Joel Benitez 2025-1049" \
            https://ntfy.sh/devops-itla
